from datetime import datetime


def generate_insight(
    predicted_price,
    historical_avg,
    historical_max,
    historical_min,
    live_price,
    latest_date,
    commodity,
    market,
    state,
    district,
    df,
):
    """
    Generate AI-style insight for AgroMate.
    """

    lines = []

    lines.append("## 🌾 AgroMate AI Market Insight\n")

    lines.append(f"**Commodity:** {commodity}")
    lines.append(f"**Market:** {market}")
    lines.append(f"**District:** {district}")
    lines.append(f"**State:** {state}")

    if latest_date is not None:
        lines.append(f"**Latest Historical Date:** {latest_date}")

    lines.append("")

    # ---------------- Prediction ----------------

    lines.append("### 🤖 ML Prediction")

    lines.append(
        f"Predicted Price : ₹{predicted_price:,.2f} / Quintal"
    )

    lines.append("")

    # ---------------- Historical ----------------

    lines.append("### 📊 Historical Analysis")

    lines.append(
        f"Average Price : ₹{historical_avg:,.2f}"
    )

    lines.append(
        f"Highest Price : ₹{historical_max:,.2f}"
    )

    lines.append(
        f"Lowest Price : ₹{historical_min:,.2f}"
    )

    lines.append("")

    # ---------------- Live ----------------

    lines.append("### 🌐 Live Market")

    if live_price is None:

        lines.append(
            "Live market price is currently unavailable."
        )

    else:

        lines.append(
            f"Current Live Price : ₹{live_price:,.2f}"
        )

        difference = predicted_price - live_price

        if difference > 0:

            lines.append(
                f"Prediction is ₹{difference:,.2f} HIGHER than today's live market."
            )

        elif difference < 0:

            lines.append(
                f"Prediction is ₹{abs(difference):,.2f} LOWER than today's live market."
            )

        else:

            lines.append(
                "Prediction matches today's live market."
            )

    lines.append("")

    # ---------------- Recommendation ----------------

    lines.append("### 💡 Recommendation")

    if live_price is not None:

        if predicted_price > live_price * 1.05:

            recommendation = "🟢 HOLD / WAIT. Prices are expected to increase."

        elif predicted_price < live_price * 0.95:

            recommendation = "🔴 SELL NOW. Prices may decrease."

        else:

            recommendation = "🟡 MARKET IS STABLE."

    else:

        if predicted_price > historical_avg:

            recommendation = (
                "🟢 Price is above historical average."
            )

        else:

            recommendation = (
                "🟡 Price is close to historical average."
            )

    lines.append(recommendation)

    lines.append("")

    # ---------------- Statistics ----------------

    lines.append("### 📈 Dataset Statistics")

    if df is not None and not df.empty:

        lines.append(
            f"Total Records : {len(df):,}"
        )

        if "Market Name" in df.columns:

            lines.append(
                f"Markets Covered : {df['Market Name'].nunique()}"
            )

        if "Commodity" in df.columns:

            lines.append(
                f"Commodities Covered : {df['Commodity'].nunique()}"
            )

    lines.append("")

    lines.append("### 🧠 AgroMate AI Summary")

    if predicted_price > historical_avg:

        lines.append(
            "The model predicts a price above the historical average, indicating stronger market conditions."
        )

    elif predicted_price < historical_avg:

        lines.append(
            "The predicted price is below the historical average, indicating a softer market."
        )

    else:

        lines.append(
            "The predicted price is close to the historical average."
        )

    lines.append("")
    lines.append("Generated by AgroMate AI 🌱")

    return "\n".join(lines)